#!/usr/bin/env bash
# install-client.sh -- install the studio CLI on the MacBook.
#
# This script is interactive. It does NOT touch ~/.zshrc -- if the user
# still has the old zsh `studio()` function defined there, the script
# prints instructions to remove it manually.
#
# Run on the MacBook (NOT the Mac Studio):
#
#   cd ~/Projects/SSH/studio-cli
#   bash deploy/install-client.sh

set -euo pipefail

PROG="install-client.sh"
CONFIG_DIR="${HOME}/.config/studio-cli"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
TOKEN_FILE="${CONFIG_DIR}/token"

DEFAULT_COLLECTOR_URL="http://100.80.21.79:8765"
DEFAULT_SSH_HOST="macstudio"

REPO_DIR=""
NON_INTERACTIVE="0"
COLLECTOR_URL=""
SSH_HOST=""
TOKEN_VALUE=""

print_usage() {
    cat <<EOF
Usage: bash ${PROG} [options]

Options:
  --repo-dir PATH         Path to the studio-cli repo (default: auto-detect)
  --collector-url URL     Collector URL (default: ${DEFAULT_COLLECTOR_URL})
  --ssh-host HOST         SSH alias for the Mac Studio (default: ${DEFAULT_SSH_HOST})
  --token TOKEN           Bearer token (skip the prompt)
  --non-interactive       Fail rather than prompting if a value is missing
  --help, -h              Show this message

This script:
  1. Verifies python3.12+ and uv are installed.
  2. Creates ${CONFIG_DIR} (mode 0700).
  3. Writes ${CONFIG_FILE} and ${TOKEN_FILE} (mode 0600).
  4. Runs 'uv pip install .[client]' from the repo dir.
  5. Verifies 'studio version' and 'studio status' work.
  6. Prints instructions for removing the legacy zsh studio() function.
EOF
}

log() {
    printf '[%s] %s\n' "${PROG}" "$*"
}

die() {
    printf '[%s] error: %s\n' "${PROG}" "$*" >&2
    exit 1
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --repo-dir) REPO_DIR="${2:-}"; shift 2 ;;
            --collector-url) COLLECTOR_URL="${2:-}"; shift 2 ;;
            --ssh-host) SSH_HOST="${2:-}"; shift 2 ;;
            --token) TOKEN_VALUE="${2:-}"; shift 2 ;;
            --non-interactive) NON_INTERACTIVE="1"; shift ;;
            --help|-h) print_usage; exit 0 ;;
            *) die "unknown argument: $1 (try --help)" ;;
        esac
    done
}

require_darwin() {
    if [[ "$(uname -s)" != "Darwin" ]]; then
        die "this script only runs on macOS"
    fi
}

detect_repo_dir() {
    if [[ -n "${REPO_DIR}" ]]; then
        return
    fi
    local script_dir
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    REPO_DIR="$(cd "${script_dir}/.." && pwd)"
    if [[ ! -f "${REPO_DIR}/pyproject.toml" ]]; then
        die "could not auto-detect repo dir; pass --repo-dir PATH"
    fi
}

require_python() {
    if ! command -v python3 >/dev/null 2>&1; then
        die "python3 not found; install Python 3.12+ first"
    fi
    local v
    v="$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
    if [[ "$(printf '%s\n3.12\n' "${v}" | sort -V | head -n1)" != "3.12" ]]; then
        die "python 3.12+ required; found ${v}"
    fi
}

require_uv() {
    if command -v uv >/dev/null 2>&1; then
        return
    fi
    if [[ "${NON_INTERACTIVE}" == "1" ]]; then
        die "uv not found and --non-interactive was set; install uv first (brew install uv)"
    fi
    log "uv not found; install with: brew install uv"
    read -r -p "Run 'brew install uv' now? [y/N] " ans
    case "${ans}" in
        y|Y|yes|YES)
            brew install uv
            ;;
        *)
            die "uv is required; please install it manually and re-run"
            ;;
    esac
}

prompt_if_missing() {
    if [[ -z "${COLLECTOR_URL}" ]]; then
        if [[ "${NON_INTERACTIVE}" == "1" ]]; then
            COLLECTOR_URL="${DEFAULT_COLLECTOR_URL}"
        else
            read -r -p "Collector URL [${DEFAULT_COLLECTOR_URL}]: " COLLECTOR_URL
            COLLECTOR_URL="${COLLECTOR_URL:-${DEFAULT_COLLECTOR_URL}}"
        fi
    fi
    if [[ -z "${SSH_HOST}" ]]; then
        if [[ "${NON_INTERACTIVE}" == "1" ]]; then
            SSH_HOST="${DEFAULT_SSH_HOST}"
        else
            read -r -p "SSH host alias [${DEFAULT_SSH_HOST}]: " SSH_HOST
            SSH_HOST="${SSH_HOST:-${DEFAULT_SSH_HOST}}"
        fi
    fi
    if [[ -z "${TOKEN_VALUE}" ]]; then
        if [[ "${NON_INTERACTIVE}" == "1" ]]; then
            die "no --token provided and --non-interactive was set"
        fi
        printf 'Bearer token (paste from /etc/studiod/token on the Mac Studio): '
        # -s hides the echo
        read -r -s TOKEN_VALUE
        printf '\n'
        if [[ -z "${TOKEN_VALUE}" ]]; then
            die "no token provided"
        fi
    fi
}

write_config() {
    install -d -m 0700 "${CONFIG_DIR}"
    log "writing ${CONFIG_FILE}"
    cat > "${CONFIG_FILE}" <<EOF
# studio-cli client configuration
# Generated by ${PROG} on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

collector_url = "${COLLECTOR_URL}"
token_file = "${TOKEN_FILE}"
timeout_seconds = 5.0
ssh_host = "${SSH_HOST}"
EOF
    chmod 0600 "${CONFIG_FILE}"

    log "writing ${TOKEN_FILE}"
    umask 077
    printf '%s\n' "${TOKEN_VALUE}" > "${TOKEN_FILE}"
    chmod 0600 "${TOKEN_FILE}"
}

install_package() {
    log "uv pip install ${REPO_DIR}[client]"
    (cd "${REPO_DIR}" && uv pip install ".[client]")
}

verify() {
    if ! command -v studio >/dev/null 2>&1; then
        log "warning: 'studio' is not on PATH after install"
        log "  fallback: alias studio='python -m studio_cli'"
        return
    fi
    log "running: studio version"
    studio version || log "warning: studio version failed"
    log "running: studio status"
    studio status || log "warning: studio status failed (collector reachable?)"
}

print_zshrc_hint() {
    cat <<EOF

------------------------------------------------------------
The 'studio' command is now provided by the studio-cli package.

If your ~/.zshrc still has a hand-written 'studio()' function (the
46-line fzf-based picker), remove that block manually -- this script
deliberately does NOT touch ~/.zshrc.

If the 'studio' command is not on your PATH after this install
(common with pyenv setups), add this shim to ~/.zshrc instead:

    studio() { python -m studio_cli "\$@"; }

To verify everything is wired up:

    studio version
    studio status
    studio
------------------------------------------------------------
EOF
}

main() {
    parse_args "$@"
    require_darwin
    detect_repo_dir
    require_python
    require_uv
    prompt_if_missing
    write_config
    install_package
    verify
    print_zshrc_hint
}

main "$@"
